apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    name: k8s-vault-store
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: tailscale-creds