apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: cert-manager-webhook-ovh
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh
    targetRevision: 0.8.1-alpha.0
    helm:
      valuesObject:
        configVersion: 0.0.2
        groupName: acme.mrobert.fr
        issuers:
          - name: letsencrypt-prod
            create: true
            kind: ClusterIssuer
            acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
            email: matthieurobert82@gmail.com
            ovhEndpointName: ovh-eu
            ovhAuthenticationMethod: application
            ovhAuthenticationRef:
              applicationKeyRef:
                name: ovh-api
                key: application_key
              applicationSecretRef:
                name: ovh-api
                key: application_secret
              applicationConsumerKeyRef:
                name: ovh-api
                key: consumer_key
  # - path: modules/base/manifests/cert-manager-ovh
  #   repoURL: https://github.com/matthieurobert/homelab.git
  #   targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      