apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-proxmox
  namespace: argocd
spec:
  destination:
    namespace: csi-proxmox
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: charts/proxmox-csi-plugin
    repoURL: https://github.com/sergelogvinov/proxmox-csi-plugin.git
    targetRevision: main
    helm:
      valuesObject:
        existingConfigSecret: proxmox-csi-plugin

        # Define the storage classes
        storageClass:
          - name: proxmox-zfs-xfs
            storage: samsung-ssds
            reclaimPolicy: Delete
            fstype: xfs
            ssd: true
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
  - path: modules/base/manifests/csi-proxmox
    repoURL: https://github.com/matthieurobert/homelab.git
    targetRevision: main
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true