apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Standard CRDs
    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.2.0
      path: config/crd/standard
      directory:
        include: "{gateway.networking.k8s.io_gateways.yaml,gateway.networking.k8s.io_gatewayclasses.yaml,gateway.networking.k8s.io_httproutes.yaml,gateway.networking.k8s.io_tcproutes.yaml,gateway.networking.k8s.io_udproutes.yaml}"
    # Experimental CRDs (TLSRoutes)
    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.2.0
      path: config/crd/experimental
      directory:
        include: "{gateway.networking.k8s.io_tlsroutes.yaml}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
