apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  sources:
  - repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    chart: metallb
  - path: kome/modules/base/manifests/metallb
    repoURL: https://github.com/matthieurobert/homelab.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - CreateNamespace=true