apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-cnpg
spec:
  secretStoreRef:
    name: k8s-vault-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: keycloak-cnpg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin
spec:
  secretStoreRef:
    name: k8s-vault-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: keycloak-admin