apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
    path: kubernetes/
    targetRevision: 26.3.4
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true