apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ovh-api
  namespace: cert-manager
spec:
  secretStoreRef:
    name: k8s-vault-store
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: ovh-api