apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: datalab/modules/
    repoURL: https://github.com/matthieurobert/homelab.git
    targetRevision: main
    directory:
      recurse: true
      include: '*/applications/*'