apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.80.3
    helm:
      valuesObject:
        apiServerProxyConfig:
          mode: "true"
        operatorConfig:
          hostname: "coffee-tailscale-operator"
  - path: datalab/modules/operators/manifests/tailscale-operator
    repoURL: https://github.com/matthieurobert/homelab.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      